export const Integrations = [
  {
    name: "PostgreSQL",
    isPlugin: true,
    category: "Databases",
    soon: false,
    desc: "A powerful, open source object-relational database system",
  },
  {
    name: "Redis",
    isPlugin: true,
    category: "Databases",
    soon: false,
    desc: "An in-memory data structure store, in-memory key–value database, cache and message broker",
  },
  {
    name: "MongoDB",
    isPlugin: true,
    category: "Databases",
    soon: false,
    desc: "A source-available cross-platform document-oriented database program",
  },
  {
    name: "MySQL",
    isPlugin: true,
    category: "Databases",
    soon: false,
    desc: "An open-source relational database management system",
  },
  {
    name: "SurrealDB",
    isPlugin: false,
    category: "Databases",
    soon: true,
    desc: "A scalable, distributed, collaborative, document-graph database, for the realtime web",
  },
  {
    name: "PocketBase",
    isPlugin: false,
    category: "Databases",
    soon: false,
    desc: "Open Source realtime backend in 1 file",
  },
  {
    name: "Quirrel",
    isPlugin: false,
    category: "Queues",
    soon: false,
    desc: "The Task Queueing Solution for Serverless",
  },
  {
    name: "Hasura",
    isPlugin: false,
    category: "Databases",
    soon: false,
    desc: "Instant GraphQL APIs for your PostgreSQL database",
  },
  {
    name: "Soketi",
    isPlugin: false,
    category: "Websockets",
    soon: false,
    desc: "An open-source Websockets server",
  },
];
