package new

import (
	"fmt"
	"runtime"

	"github.com/abdfnx/botway/constants"
	"github.com/abdfnx/botway/internal/options"
	"github.com/charmbracelet/lipgloss"
)

var (
	prim   = lipgloss.NewStyle().Foreground(constants.PRIMARY_COLOR)
	subtle = lipgloss.NewStyle().Foreground(constants.GRAY_COLOR)
	dot    = lipgloss.NewStyle().Foreground(constants.GRAY_COLOR).SetString(" • ").String()
	opts   = options.CommonOptions{
		BotName: "",
	}
)

func checkbox(label string, checked bool) string {
	if checked {
		return prim.Render("[✔] " + label)
	}

	return fmt.Sprintf("[ ] %s", label)
}

func BotType(m model) string {
	if m.PlatformChoice == 0 {
		return "discord"
	} else if m.PlatformChoice == 1 {
		return "telegram"
	} else if m.PlatformChoice == 2 {
		return "slack"
	}

	return ""
}

func BotLang(m model) string {
	if m.LangChoice == 0 {
		return "python"
	} else if m.LangChoice == 1 {
		if m.PlatformChoice == 2 {
			return "nodejs"
		} else {
			return "go"
		}
	} else if m.LangChoice == 2 {
		return "nodejs"
	} else if m.LangChoice == 3 {
		return "ruby"
	} else if m.LangChoice == 4 {
		return "rust"
	} else if m.LangChoice == 5 {
		return "deno"
	} else if m.LangChoice == 6 {
		return "csharp"
	} else if m.LangChoice == 7 {
		return "crystal"
	} else if m.LangChoice == 8 {
		return "dart"
	}

	return ""
}

func BotStartCmd(m model) string {
	nodeCmd := "node src/index.js"

	if m.LangChoice == 0 && m.PMCoice == 0 {
		if runtime.GOOS == "windows" {
			return `py .\src\main.py`
		} else {
			return `python3 ./src/main.py`
		}
	} else if m.LangChoice == 0 && m.PMCoice == 1 {
		if runtime.GOOS == "windows" {
			return `pipenv run py .\src\main.py`
		} else {
			return `pipenv run python3 ./src/main.py`
		}
	} else if m.LangChoice == 0 && m.PMCoice == 2 {
		if runtime.GOOS == "windows" {
			return `poetry run .\src\main.py`
		} else {
			return `poetry run ./src/main.py`
		}
	} else if m.LangChoice == 1 {
		if m.PlatformChoice == 2 {
			return nodeCmd
		} else {
			return "go run src/main.go"
		}
	} else if m.LangChoice == 2 {
		return nodeCmd
	} else if m.LangChoice == 3 {
		return "bundle exec ruby src/main.rb"
	} else if m.LangChoice == 4 {
		return "cargo run src/main.rs"
	} else if m.LangChoice == 5 {
		return "deno run --allow-all src/main.ts"
	} else if m.LangChoice == 6 {
		return "dotnet run"
	} else if m.LangChoice == 7 {
		return "crystal run src/main.cr"
	} else if m.LangChoice == 8 {
		return "dart run src/main.dart"
	}

	return ""
}

func BotPM(m model) string {
	if m.LangChoice == 0 && m.PMCoice == 0 {
		return "pip"
	} else if m.LangChoice == 0 && m.PMCoice == 1 {
		return "pipenv"
	} else if m.LangChoice == 0 && m.PMCoice == 2 {
		return "poetry"
	} else if m.LangChoice == 1  {
		return "go mod"
	} else if m.LangChoice == 2 && m.PMCoice == 0 {
		return "npm"
	} else if m.LangChoice == 2 && m.PMCoice == 1 {
		return "yarn"
	} else if m.LangChoice == 2 && m.PMCoice == 2 {
		return "pnpm"
	} else if m.LangChoice == 3 {
		return "bundler"
	} else if m.LangChoice == 4 && m.PMCoice == 0 {
		return "cargo"
	} else if m.LangChoice == 4 && m.PMCoice == 1 {
		return "fleet"
	} else if m.LangChoice == 5 {
		return "deno"
	} else if m.LangChoice == 6 {
		return "dotnet"
	} else if m.LangChoice == 7 {
		return "shards"
	} else if m.LangChoice == 8 {
		return "pub"
	}

	return ""
}

func CSharpGitIgnore() string {
	return `## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# User-specific files
*.suo
*.user
*.userosscache
*.sln.docstates

# User-specific files (MonoDevelop/Xamarin Studio)
*.userprefs

# Build results
[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
build/
bld/
[Bb]in/
[Oo]bj/

# Visual Studo 2015 cache/options directory
.vs/

# MSTest test Results
[Tt]est[Rr]esult*/
[Bb]uild[Ll]og.*

# NUNIT
*.VisualState.xml
TestResult.xml

# Build Results of an ATL Project
[Dd]ebugPS/
[Rr]eleasePS/
dlldata.c

*_i.c
*_p.c
*_i.h
*.ilk
*.meta
*.obj
*.pch
*.pdb
*.pgc
*.pgd
*.rsp
*.sbr
*.tlb
*.tli
*.tlh
*.tmp
*.tmp_proj
*.log
*.vspscc
*.vssscc
.builds
*.pidb
*.svclog
*.scc

# Chutzpah Test files
_Chutzpah*

# Visual C++ cache files
ipch/
*.aps
*.ncb
*.opensdf
*.sdf
*.cachefile

# Visual Studio profiler
*.psess
*.vsp
*.vspx

# TFS 2012 Local Workspace
$tf/

# Guidance Automation Toolkit
*.gpState

# ReSharper is a .NET coding add-in
_ReSharper*/
*.[Rr]e[Ss]harper
*.DotSettings.user

# JustCode is a .NET coding addin-in
.JustCode

# TeamCity is a build add-in
_TeamCity*

# DotCover is a Code Coverage Tool
*.dotCover

# NCrunch
_NCrunch_*
.*crunch*.local.xml

# MightyMoose
*.mm.*
AutoTest.Net/

# Web workbench (sass)
.sass-cache/

# Installshield output folder
[Ee]xpress/

# DocProject is a documentation generator add-in
DocProject/buildhelp/
DocProject/Help/*.HxT
DocProject/Help/*.HxC
DocProject/Help/*.hhc
DocProject/Help/*.hhk
DocProject/Help/*.hhp
DocProject/Help/Html2
DocProject/Help/html

# Click-Once directory
publish/

# Publish Web Output
*.[Pp]ublish.xml
*.azurePubxml
# TODO: Comment the next line if you want to checkin your web deploy settings
# but database connection strings (with potential passwords) will be unencrypted
*.pubxml
*.publishproj

# NuGet Packages
*.nupkg
# The packages folder can be ignored because of Package Restore
**/packages/*
# except build/, which is used as an MSBuild target.
!**/packages/build/
# Uncomment if necessary however generally it will be regenerated when needed
#!**/packages/repositories.config

# Windows Azure Build Output
csx/
*.build.csdef

# Windows Store app package directory
AppPackages/

# Others
*.[Cc]ache
ClientBin/
~$*
*~
*.dbmdl
*.dbproj.schemaview
*.pfx
*.publishsettings
node_modules/
bower_components/

# RIA/Silverlight projects
Generated_Code/

# Backup & report files from converting an old project file
# to a newer Visual Studio version. Backup files are not needed,
# because we have git ;-)
_UpgradeReport_Files/
Backup*/
UpgradeLog*.XML
UpgradeLog*.htm

# SQL Server files
*.mdf
*.ldf

# Business Intelligence projects
*.rdl.data
*.bim.layout
*.bim_*.settings

# Microsoft Fakes
FakesAssemblies/

# Node.js Tools for Visual Studio
.ntvs_analysis.dat

# Visual Studio 6 build log
*.plg

# Visual Studio 6 workspace options file
*.opt

#Custom
project.lock.json
*.pyc
/.editorconfig

\.idea/

# Codealike UID
codealike.json`
}
