export const ValidateProps = {
  user: {
    username: { type: "string", minLength: 4, maxLength: 20 },
    name: { type: "string", minLength: 1, maxLength: 50 },
    password: { type: "string", minLength: 8 },
    email: { type: "string", minLength: 1 },
    githubApiToken: { type: "string", maxLength: 40 },
    railwayApiToken: { type: "string", maxLength: 36 },
    renderApiToken: { type: "string", maxLength: 32 },
    isAdmin: { type: "boolean" },
    projects: { type: "array" },
  },
  project: {
    name: { type: "string", minLength: 1, maxLength: 350 },
    icon: { type: "string" },
    repo: { type: "string" },
    buildCommand: { type: "string" },
    startCommand: { type: "string" },
    rootDirectory: { type: "string" },
    visibility: { type: "string", minLength: 6, maxLength: 7 },
    platform: { type: "string", minLength: 5, maxLength: 8 },
    lang: { type: "string", minLength: 1, maxLength: 50 },
    packageManager: { type: "string", minLength: 1, maxLength: 50 },
    hostService: { type: "string", minLength: 1, maxLength: 50 },
    botToken: { type: "string", maxLength: 100 },
    botAppToken: { type: "string", maxLength: 100 },
    botSecretToken: { type: "string", maxLength: 100 },
    railwayProjectId: { type: "string", maxLength: 38 },
    railwayServiceId: { type: "string", maxLength: 38 },
    railwayEnvId: { type: "string", maxLength: 38 },
    renderServiceId: { type: "string", maxLength: 24 },
    repoBranch: { type: "string" },
    pullRequestPreviewsEnabled: { type: "string", maxLength: 3 },
  },
};
