[package]
name = "botway-rs"
version = "0.2.2"
authors = ["Abdfn", "David Tomson"]
edition = "2021"
description = "Rust client package for Botway."
repository = "https://github.com/abdfnx/botway"
readme = "README.md"
license = "MIT"
keywords = ["botway", "bot", "api"]
include = ["src/**/*", "Cargo.toml", "LICENSE.md", "README.md"]

[lib]
name = "botway_rs"
path = "src/lib.rs"

[dependencies]
yaml-rust = "0.4"
rustc-serialize = "0.3.24"
snailquote = "0.3.1"
dirs = "5.0.0"
